export const GET_ALL_COMMENT_API = 'GET_ALL_COMMENT_API';
export const INSERT_COMMENT_API = 'INSERT_COMMENT_API';
export const UPDATE_COMMENT_API = 'UPDATE_COMMENT_API';
export const DELETE_COMMENT_API = 'DELETE_COMMENT_API';

export const GET_ALL_COMMENT = 'GET_ALL_COMMENT';

export const ID_COMMENT = 'ID_COMMENT';